// =============================================================================
// src/exam/content.ts
// Authored exam content per level: a reading passage + comprehension questions,
// listening scripts + comprehension questions, and production prompts. A0
// reuses the A1 set. Strutture (grammar) items are generated by the quiz engine
// in builder.ts, not authored here.
// =============================================================================

import type { CefrLevel } from "../types/index.js";

export interface ComprehensionQ {
  question: string;
  options: string[];
  correctIndex: number;
}
export interface AscoltoContent {
  audioText: string;
  question: string;
  options: string[];
  correctIndex: number;
}
export interface LevelContent {
  passage: { title: string; text: string };
  lettura: ComprehensionQ[];
  ascolto: AscoltoContent[];
  scritta: { prompt: string; minWords: number };
  orale: { prompt: string; minWords: number };
}

const A1: LevelContent = {
  passage: {
    title: "La giornata di Luca",
    text:
      "Mi chiamo Luca. Ho ventidue anni e abito a Bologna con la mia famiglia. " +
      "Studio ingegneria all'università. La mattina prendo un caffè e vado a lezione " +
      "in autobus. La sera mangio con i miei genitori e poi guardo la televisione.",
  },
  lettura: [
    { question: "Dove abita Luca?", options: ["Bologna", "Roma", "Milano", "Napoli"], correctIndex: 0 },
    { question: "Cosa studia Luca?", options: ["Medicina", "Ingegneria", "Legge", "Lingue"], correctIndex: 1 },
    { question: "Come va a lezione?", options: ["A piedi", "In autobus", "In treno", "In bici"], correctIndex: 1 },
  ],
  ascolto: [
    {
      audioText: "Il treno per Roma parte alle nove e mezza dal binario tre.",
      question: "A che ora parte il treno?",
      options: ["Alle otto", "Alle nove e mezza", "Alle dieci", "Alle nove"],
      correctIndex: 1,
    },
    {
      audioText: "Vorrei un caffè e un cornetto, per favore.",
      question: "Dove si trova probabilmente la persona?",
      options: ["In banca", "Al bar", "In farmacia", "A scuola"],
      correctIndex: 1,
    },
    {
      audioText: "Oggi fa freddo e piove, quindi prendo l'ombrello.",
      question: "Com'è il tempo oggi?",
      options: ["Caldo e sole", "Freddo e pioggia", "Nevoso", "Ventoso"],
      correctIndex: 1,
    },
  ],
  scritta: { prompt: "Scrivi una breve email a un amico per invitarlo a cena.", minWords: 30 },
  orale: { prompt: "Presentati: nome, età, dove abiti e cosa ti piace fare.", minWords: 25 },
};

const A2: LevelContent = {
  passage: {
    title: "La giornata di Marta",
    text:
      "Ieri Marta è andata al mercato per comprare frutta e verdura. Ha speso venti euro. " +
      "Dopo è tornata a casa e ha preparato una zuppa per la cena. La sera è venuta la sua " +
      "amica Giulia e hanno guardato un film insieme. Marta era molto stanca ma contenta.",
  },
  lettura: [
    { question: "Dove è andata Marta ieri?", options: ["Al cinema", "Al mercato", "In palestra", "Al lavoro"], correctIndex: 1 },
    { question: "Quanto ha speso?", options: ["Dieci euro", "Venti euro", "Trenta euro", "Cinquanta euro"], correctIndex: 1 },
    { question: "Cosa hanno fatto la sera?", options: ["Hanno cucinato", "Hanno ballato", "Hanno guardato un film", "Hanno studiato"], correctIndex: 2 },
  ],
  ascolto: [
    {
      audioText: "Scusi, per andare alla stazione devo girare a destra o a sinistra?",
      question: "Cosa chiede la persona?",
      options: ["L'ora", "La strada per la stazione", "Il prezzo", "Il menu"],
      correctIndex: 1,
    },
    {
      audioText: "Ho prenotato un tavolo per quattro persone alle otto di sera.",
      question: "Per quante persone è la prenotazione?",
      options: ["Due", "Tre", "Quattro", "Otto"],
      correctIndex: 2,
    },
    {
      audioText: "La riunione di domani è stata spostata a venerdì pomeriggio.",
      question: "Quando sarà la riunione?",
      options: ["Domani mattina", "Venerdì pomeriggio", "Lunedì", "Stasera"],
      correctIndex: 1,
    },
  ],
  scritta: { prompt: "Racconta cosa hai fatto lo scorso fine settimana.", minWords: 50 },
  orale: { prompt: "Descrivi la tua giornata tipica.", minWords: 40 },
};

const B1: LevelContent = {
  passage: {
    title: "Lavorare da casa",
    text:
      "Da quando lavoro da casa, la mia routine è cambiata molto. Prima passavo due ore al " +
      "giorno sui mezzi pubblici; adesso uso quel tempo per fare sport e cucinare piatti sani. " +
      "Tuttavia, mi manca il contatto con i colleghi e a volte mi sento isolato. Penso che " +
      "l'equilibrio ideale sia un modello ibrido, con alcuni giorni in ufficio e altri a casa.",
  },
  lettura: [
    {
      question: "Cosa faceva prima l'autore con due ore al giorno?",
      options: ["Faceva sport", "Viaggiava sui mezzi pubblici", "Cucinava", "Dormiva"],
      correctIndex: 1,
    },
    {
      question: "Cosa gli manca del lavoro in ufficio?",
      options: ["Lo stipendio", "Il contatto con i colleghi", "Il caffè", "Il computer"],
      correctIndex: 1,
    },
    {
      question: "Quale modello preferisce?",
      options: ["Solo casa", "Solo ufficio", "Un modello ibrido", "Nessuno"],
      correctIndex: 2,
    },
  ],
  ascolto: [
    {
      audioText: "Se avessi saputo che l'ingresso era gratuito, sarei venuto anch'io.",
      question: "Perché la persona non è venuta?",
      options: ["Non aveva tempo", "Pensava di dover pagare", "Era malata", "Non le interessava"],
      correctIndex: 1,
    },
    {
      audioText: "Il pacco arriverà entro tre giorni lavorativi, esclusi i festivi.",
      question: "Quando arriva il pacco?",
      options: ["Oggi", "Entro tre giorni lavorativi", "Tra un mese", "Mai"],
      correctIndex: 1,
    },
    {
      audioText: "Nonostante il traffico, siamo riusciti ad arrivare in orario.",
      question: "Sono arrivati in ritardo?",
      options: ["Sì, molto", "No, in orario", "Non sono arrivati", "Un'ora dopo"],
      correctIndex: 1,
    },
  ],
  scritta: { prompt: "Descrivi i vantaggi e gli svantaggi di vivere in una grande città.", minWords: 80 },
  orale: { prompt: "Racconta un viaggio o un'esperienza che ti ha colpito.", minWords: 60 },
};

const B2: LevelContent = {
  passage: {
    title: "Imparare una lingua",
    text:
      "L'apprendimento di una lingua straniera non dipende soltanto dal talento, ma soprattutto " +
      "dalla costanza. Molti studenti si scoraggiano dopo poche settimane perché si aspettano " +
      "risultati immediati. In realtà, i progressi diventano evidenti solo quando si accumulano " +
      "centinaia di ore di pratica. Chi riesce a integrare la lingua nella vita quotidiana — " +
      "guardando film, leggendo articoli o parlando con madrelingua — ottiene risultati nettamente " +
      "migliori rispetto a chi studia solo sui libri.",
  },
  lettura: [
    {
      question: "Da cosa dipende soprattutto l'apprendimento secondo il testo?",
      options: ["Dal talento", "Dalla costanza", "Dai libri", "Dall'età"],
      correctIndex: 1,
    },
    {
      question: "Perché molti studenti si scoraggiano?",
      options: ["Non hanno tempo", "Si aspettano risultati immediati", "Non hanno insegnanti", "Sono troppo vecchi"],
      correctIndex: 1,
    },
    {
      question: "Chi ottiene risultati migliori?",
      options: [
        "Chi studia solo sui libri",
        "Chi ha talento naturale",
        "Chi integra la lingua nella vita quotidiana",
        "Chi vive all'estero",
      ],
      correctIndex: 2,
    },
  ],
  ascolto: [
    {
      audioText: "Il candidato ha sottolineato che le riforme, per quanto necessarie, richiederanno tempo e sacrifici.",
      question: "Cosa pensa il candidato delle riforme?",
      options: ["Sono inutili", "Sono necessarie ma richiedono tempo", "Sono già finite", "Non servono sacrifici"],
      correctIndex: 1,
    },
    {
      audioText: "A causa dello sciopero dei trasporti, si consiglia di posticipare gli spostamenti non urgenti.",
      question: "Cosa si consiglia?",
      options: ["Di scioperare", "Di rimandare gli spostamenti non urgenti", "Di prendere l'aereo", "Di camminare"],
      correctIndex: 1,
    },
    {
      audioText: "Sebbene il film abbia ricevuto critiche contrastanti, ha incassato milioni al botteghino.",
      question: "Com'è andato il film al botteghino?",
      options: ["Male", "Ha incassato molto", "Non è uscito", "È stato ritirato"],
      correctIndex: 1,
    },
  ],
  scritta: { prompt: "Esprimi la tua opinione: la tecnologia ci rende più liberi o più dipendenti?", minWords: 120 },
  orale: { prompt: "Sostieni una tesi: è meglio studiare all'estero o nel proprio paese?", minWords: 90 },
};

const CONTENT: Record<Exclude<CefrLevel, "A0">, LevelContent> = { A1, A2, B1, B2 };

/** Exam content for a level; A0 reuses the A1 set. */
export function contentForLevel(level: CefrLevel): LevelContent {
  return CONTENT[level === "A0" ? "A1" : level];
}
