// =============================================================================
// src/pages/Verbs.tsx
// A conjugation reference. Pick any verb from the lexicon and see its full
// paradigm — every mood and tense — generated live by the Phase 1 engine. Tap any
// form to hear it. Search by Italian or English.
// =============================================================================

import { useMemo, useState } from "react";
import { Badge, Card, PageHead } from "../ui/components.js";
import { useSpeech } from "../hooks/useSpeech.js";
import type { UseSpeech } from "../hooks/useSpeech.js";
import { conjugateAll } from "../engine/conjugator.js";
import { VERB_LIST } from "../data/verbs.js";
import { PERSONS } from "../types/index.js";
import type { Paradigm, Verb } from "../types/index.js";

const INDICATIVO: [string, string][] = [
  ["presente", "Presente"],
  ["passatoProssimo", "Passato prossimo"],
  ["imperfetto", "Imperfetto"],
  ["futuroSemplice", "Futuro semplice"],
  ["passatoRemoto", "Passato remoto"],
  ["trapassatoProssimo", "Trapassato prossimo"],
  ["futuroAnteriore", "Futuro anteriore"],
  ["trapassatoRemoto", "Trapassato remoto"],
];
const CONGIUNTIVO: [string, string][] = [
  ["presente", "Presente"],
  ["passato", "Passato"],
  ["imperfetto", "Imperfetto"],
  ["trapassato", "Trapassato"],
];
const CONDIZIONALE: [string, string][] = [
  ["presente", "Presente"],
  ["passato", "Passato"],
];

export function Verbs() {
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<string>("essere");
  const speech = useSpeech();

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return VERB_LIST;
    return VERB_LIST.filter((v) => v.infinitive.includes(q) || v.translation.toLowerCase().includes(q));
  }, [search]);

  const verb: Verb | undefined = VERB_LIST.find((v) => v.infinitive === selected) ?? filtered[0];
  const full = verb ? conjugateAll(verb) : null;

  return (
    <>
      <PageHead
        title="Verb tables"
        sub="The full paradigm of any verb, generated by the same engine the drill uses. Tap a form to hear it. Irregular forms are handled from a verified override table."
      />

      <Card>
        <input
          className="qinput"
          style={{ marginBottom: 12, fontSize: "0.95rem", padding: 9 }}
          placeholder="Search verbs (Italian or English)…"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        <div className="verb-chips">
          {filtered.map((v) => (
            <button
              key={v.infinitive}
              className={`chip-link${v.infinitive === selected ? " chip-link--active" : ""}`}
              onClick={() => setSelected(v.infinitive)}
            >
              {v.infinitive}
            </button>
          ))}
          {filtered.length === 0 && <p className="muted">No verbs match “{search}”.</p>}
        </div>
      </Card>

      {verb && full && (
        <div style={{ marginTop: 24 }}>
          <div className="row" style={{ gap: 10, flexWrap: "wrap", marginBottom: 16, alignItems: "baseline" }}>
            <h2 style={{ textTransform: "none" }}>{verb.infinitive}</h2>
            <span className="muted">{verb.translation}</span>
            <Badge>{verb.cefrLevel}</Badge>
            <Badge variant={verb.isIrregular ? "accent" : "good"}>{verb.isIrregular ? "irregular" : "regular"}</Badge>
            <Badge>aux: {verb.auxiliary}</Badge>
          </div>

          <Card title="Non-finite forms">
            <div className="verb-nonfinite">
              <NonFinite label="Gerund" value={full.nonFinite.gerund} speech={speech} />
              <NonFinite label="Past participle" value={full.nonFinite.pastParticiple} speech={speech} />
              <NonFinite label="Present participle" value={full.nonFinite.presentParticiple} speech={speech} />
            </div>
          </Card>

          <div style={{ marginTop: 16 }}>
            <MoodTable title="Indicativo" tenses={INDICATIVO} data={full.indicativo} speech={speech} />
          </div>
          <div style={{ marginTop: 16 }}>
            <MoodTable title="Congiuntivo" tenses={CONGIUNTIVO} data={full.congiuntivo} speech={speech} />
          </div>
          <div style={{ marginTop: 16 }}>
            <MoodTable title="Condizionale" tenses={CONDIZIONALE} data={full.condizionale} speech={speech} />
          </div>
          <div style={{ marginTop: 16 }}>
            <MoodTable title="Imperativo" tenses={[["presente", "Presente"]]} data={full.imperativo} speech={speech} />
          </div>
        </div>
      )}
    </>
  );
}

function NonFinite(props: { label: string; value: string; speech: UseSpeech }) {
  return (
    <div className="verb-nf">
      <div className="ld-label">{props.label}</div>
      <button className="verb-form verb-form--lg" onClick={() => props.speech.speak(props.value)} disabled={!props.speech.support.tts}>
        {props.value}
      </button>
    </div>
  );
}

function MoodTable(props: {
  title: string;
  tenses: [string, string][];
  data: Record<string, Paradigm>;
  speech: UseSpeech;
}) {
  const { tenses, data, speech } = props;
  return (
    <Card title={props.title}>
      <div style={{ overflowX: "auto" }}>
        <table className="gtable verb-table">
          <thead>
            <tr>
              <th />
              {tenses.map(([key, label]) => <th key={key}>{label}</th>)}
            </tr>
          </thead>
          <tbody>
            {PERSONS.map((person, pi) => (
              <tr key={person}>
                <th>{person}</th>
                {tenses.map(([key]) => {
                  const form = data[key]?.[pi] ?? "";
                  return (
                    <td key={key}>
                      {form ? (
                        <button className="verb-form" onClick={() => speech.speak(form)} disabled={!speech.support.tts}>
                          {form}
                        </button>
                      ) : (
                        <span className="muted">—</span>
                      )}
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Card>
  );
}
